-- After running the SSIS package, the following codes are run

-- Add NATIONALITIES.Description_ by NATIONALITIES_DESCRIPTION.txt

-- Add POSITIONS.Description_ by POSITIONS_DESCRIPTION.txt

-- Change Data Types with Design mode in SQL Server

-- Drop Column
ALTER TABLE GOALKEEPING_TEST
DROP COLUMN FullName;

-- Add Foreign Key Constraint
ALTER TABLE DEFENSIVE_TEST
ADD CONSTRAINT FK_DEFENSIVE_PLAYERS
FOREIGN KEY (PlayerID) REFERENCES PLAYERS_TEST(ID)

ALTER TABLE DRIBBLING_TEST
ADD CONSTRAINT FK_DRIBBLING_PLAYERS
FOREIGN KEY (PlayerID) REFERENCES PLAYERS_TEST(ID)

ALTER TABLE GOALKEEPING_TEST
ADD CONSTRAINT FK_GOALKEEPING_PLAYERS
FOREIGN KEY (PlayerID) REFERENCES PLAYERS_TEST(ID)

ALTER TABLE PASSING_TEST
ADD CONSTRAINT FK_PASSING_PLAYERS
FOREIGN KEY (PlayerID) REFERENCES PLAYERS_TEST(ID)

ALTER TABLE PLAYING_TIME_TEST
ADD CONSTRAINT FK_PLAYING_TIME_PLAYERS
FOREIGN KEY (PlayerID) REFERENCES PLAYERS_TEST(ID)

ALTER TABLE SHOOTING_TEST
ADD CONSTRAINT FK_SHOOTING_PLAYERS
FOREIGN KEY (PlayerID) REFERENCES PLAYERS_TEST(ID)

ALTER TABLE TEAMS_TEST
ADD CONSTRAINT FK_TEAMS_LEAGUES
FOREIGN KEY (LeagueID) REFERENCES LEAGUES_TEST(ID)

ALTER TABLE PLAYERS_TEST
ADD CONSTRAINT FK_PLAYERS_POSITIONS
FOREIGN KEY (PositionID) REFERENCES POSITIONS_TEST(ID)

ALTER TABLE PLAYERS_TEST
ADD CONSTRAINT FK_PLAYERS_TEAMS
FOREIGN KEY (TeamID) REFERENCES TEAMS_TEST(ID)

ALTER TABLE PLAYERS_TEST
ADD CONSTRAINT FK_PLAYERS_NATIONALITIES
FOREIGN KEY (NationID) REFERENCES NATIONALITIES_TEST(ID)

ALTER TABLE PLAYERS_TEST
ADD CONSTRAINT FK_PLAYERS_LEAGUES
FOREIGN KEY (LeagueID) REFERENCES LEAGUES_TEST(ID)

